### ISSUE TITLE
Can you use this to alias a command on your system for nvim?

### ISSUE THREAD

**Issue by anoduck** [notomo/aliaser.nvim#1]
You are probably going to get asked this anyway, so why not?

Can you use this to create an alias within nvim for a command on your system? Like you do in bash?

For a real life example:

I need to create an alias for tar so nvim will use gtar instead of tar.

**Comment by notomo** [comment]
Thanks for your question.

The following is the answer, though I'm not sure I understand your question.

- aliaser.nvim is not related with shell alias.
- aliaser.nvim does not provide helper to use system command. But you can use vim functions.
```lua
local aliaser = require("aliaser")

aliaser.register_factory("cmd", function(aliases)
  aliases:set("echo", function(a, b)
    local result = vim.fn.systemlist({ "echo", a, b })
    print(table.concat(result, "\n"))
  end)
end)

aliaser.call("cmd/echo", "aaa", "bbb")
-- aaa bbb
```

**Comment by anoduck** [comment]
I think that would resolve the issue that I am encountering, and that definitely answers my question concerning the plugin. 

### The context

I am cursed with insistent use of OpenBSD (it is a double edge sword...). OpenBSD does not use Gnu's `tar` command, it uses the older BSD variety. Unfortunately, mason was written to use the Gnu command, so mason reports tar as not available. So, in order to get mason to find Gnu's tar, I have to alias `tar` to `gtar` (i.e., gnu tar). 

In bash:

```bash
alias tar="/usr/local/bin/gtar"
```

https://github.com/williamboman/mason.nvim/discussions/1299

**Comment by notomo** [comment]
Thanks. I got it.

aliaser.nvim does not resolve the problem.

> aliaser.nvim is not related with shell alias.
